name: Build for Apple platforms

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: [self-hosted, macOS]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake for iOS
      env:
        SDK: "iphoneos"
        SDK_VERSION: "16.0"
      run: |
        mkdir xcarchives
        mkdir build-ios && cd build-ios
        cmake .. \
            -G Xcode \
            -DIOS=1 \
            -DCMAKE_OSX_SYSROOT=$(xcrun --sdk $SDK --show-sdk-path) \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=$SDK_VERSION \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_LIBRARY_TYPE=Static \
            -DUSE_FREETYPE=0 \
            -DUSE_FREEIMAGE=0 \
            -DUSE_OPENVR=0 \
            -DUSE_OPENGL=0 \
            -DUSE_GLES2=0 \
            -DUSE_RAPIDJSON=0 \
            -DUSE_DRACO=0 \
            -DUSE_TK=0 \
            -DUSE_TCL=0 \
            -DUSE_TBB=0 \
            -DUSE_VTK=0

    - name: Build for iOS
      working-directory: build-ios
      run: |
        xcodebuild archive \
            -project OCCT.xcodeproj \
            -scheme ALL_BUILD \
            -destination "generic/platform=iOS" \
            -archivePath "../xcarchives/occt-iOS.xcarchive" \
            INSTALL_PATH="/usr/local/lib" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            ARCHS='$(ARCHS_STANDARD)'

    - name: Build for iOS Simulator
      working-directory: build-ios
      run: |
        xcodebuild archive \
            -project OCCT.xcodeproj \
            -scheme ALL_BUILD \
            -destination "generic/platform=iOS Simulator" \
            -archivePath "../xcarchives/occt-iOSSimulator.xcarchive" \
            INSTALL_PATH="/usr/local/lib" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            ARCHS='$(ARCHS_STANDARD)'

    - name: Merge static libraries
      run: |
        for ARCHIVE in xcarchives/*.xcarchive;
        do
            libtool -static -o $ARCHIVE/Products/usr/local/lib/occt.a $ARCHIVE/Products/usr/local/lib/*.a
            echo "Created combined archive file at $ARCHIVE/Products/usr/local/lib/occt.a"
        done
    
    - name: Copy header files
      run: |
        mkdir -p xcheaders/opencascade
        cp $(sed -nr 's/\#include "(.*)"/\1/p' ./build-ios/include/opencascade/*) ./xcheaders/opencascade/

    - name: Create XCFramework bundle
      run: |
        xcodebuild -create-xcframework \
          -library xcarchives/occt-iOS.xcarchive/Products/usr/local/lib/occt.a \
          -headers xcheaders/opencascade \
          -library xcarchives/occt-iOSSimulator.xcarchive/Products/usr/local/lib/occt.a \
          -headers xcheaders/opencascade \
          -output xcframeworks/occt.xcframework

    - name: Compress XCFramework bundle
      run: zip -r xcframeworks/occt.xcframework.zip xcframeworks/occt.xcframework

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: occt.xcframework
        path: xcframeworks/occt.xcframework.zip
