name: Build for Apple platforms

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  SDK: "iphoneos"
  SDK_VERSION: "16.0"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        mkdir build && cd build
        cmake .. \
            -G Xcode \
            -DIOS=1 \
            -DCMAKE_OSX_SYSROOT=$(xcrun --sdk $SDK --show-sdk-path) \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=$SDK_VERSION \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_LIBRARY_TYPE=Static \
            -DUSE_FREETYPE=0 \
            -DUSE_FREEIMAGE=0 \
            -DUSE_OPENVR=0 \
            -DUSE_OPENGL=0 \
            -DUSE_GLES2=0 \
            -DUSE_RAPIDJSON=0 \
            -DUSE_DRACO=0 \
            -DUSE_TK=0 \
            -DUSE_TCL=0 \
            -DUSE_TBB=0 \
            -DUSE_VTK=0
        mkdir xcarchives

    - name: Build for iOS
      env:
        PLATFORM: "iOS"
      working-directory: build
      run: |
        xcodebuild archive \
            -project OCCT.xcodeproj \
            -scheme ALL_BUILD \
            -destination generic/platform=$PLATFORM \
            -archivePath "xcarchives/OCCT-$PLATFORM.xcarchive" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            ARCHS='$(ARCHS_STANDARD)' \
            BUILT_PRODUCTS_DIR='$(CONFIGURATION_BUILD_DIR)'\
            INSTALL_DIR='$(DSTROOT)$(INSTALL_PATH)'

    - name: Merge frameworks
      working-directory: build
      run: |
        for ARCHIVE in $(ls xcarchives/*.xcarchive)
        do
            libtool -static -o xcarchives/$ARCHIVE/Products/usr/local/lib/occt.a xcarchives/$ARCHIVE/Products/usr/local/lib/*.a
        done
    # lipo -create xcarchives/OCCT-iOS-Simulator-*.xcarchive/Products/usr/local/lib/occt.a -output occt-simulator.a
    
    - name: Copy header files
      working-directory: build
      run: |
        mkdir -p xcheaders/opencascade
        cp $(sed -nr 's/\#include "(.*)"/\1/p' ../include/opencascade/*) ./xcheaders/opencascade/

    - name: Create xcframework
      working-directory: build
      run: |
        mkdir xcframeworks
        xcodebuild -create-xcframework \
          -library xcarchives/OCCT-iOS.xcarchive/Products/usr/local/lib/occt.a \
          -headers xcheaders/opencascade \
          -output xcframeworks/occt.xcframework

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: occt.xcframework
        path: build/xcframeworks/occt.xcframework
